# Generated by Django 3.2 on 2021-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_farmars_farmarsrigister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmarsrigister',
            old_name='email',
            new_name='uname',
        ),
        migrations.RemoveField(
            model_name='farmarsrigister',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farmarsrigister',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmarsrigister',
            name='password',
        ),
        migrations.AddField(
            model_name='farmarsrigister',
            name='psd',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
