# Generated by Django 3.2 on 2021-05-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210519_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmarsrigister',
            old_name='uname',
            new_name='email',
        ),
    ]
