# Generated by Django 3.2 on 2021-05-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_uname_farmarsrigister_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmarsrigister',
            old_name='email',
            new_name='uname',
        ),
    ]
