# Generated by Django 3.2 on 2021-05-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_email_farmarsrigister_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmarsrigister',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmarsrigister',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
