# Generated by Django 3.2 on 2021-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210519_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desription', models.IntegerField(choices=[(0, 'sunny'), (1, 'rain'), (2, 'cloudy'), (3, 'snow')], default=0)),
                ('temputuer', models.FloatField()),
                ('create_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['create_on'],
            },
        ),
    ]
