# Generated by Django 3.2 on 2021-05-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
