# Generated by Django 3.2.5 on 2021-08-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_imagetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cause', models.TextField()),
                ('treatment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='imagetest',
            name='testImage',
            field=models.ImageField(upload_to='testimge'),
        ),
    ]
