# Generated by Django 3.2.5 on 2021-08-25 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('plant', models.CharField(choices=[('Apple', 'Apple'), ('Tomato', 'Tomato'), ('Strawberry', 'Strawberry'), ('Squash', 'Squash'), ('Soybean', 'Soybean'), ('Raspberry', 'Raspberry'), ('Potato', 'Potato'), ('Pepper', 'Pepper'), ('Peach', 'Peach'), ('Orange', 'Orange'), ('Grape', 'Grape'), ('Corn', 'Corn'), ('Cherry', 'Cherry'), ('Blueberry', 'Blueberry')], max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
