# Generated by Django 3.2.6 on 2021-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
