# Generated by Django 3.2.6 on 2021-08-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210831_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
