# Generated by Django 3.2.6 on 2021-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210901_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='lands',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
