# Generated by Django 4.1.5 on 2023-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_product_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hatem',
            field=models.CharField(default='hatem', max_length=300),
        ),
    ]
