# Generated by Django 4.1.5 on 2023-01-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_product_hatem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Battrayimage',
            field=models.ImageField(blank=True, null=True, upload_to='placeToUpload'),
        ),
        migrations.AddField(
            model_name='product',
            name='Cameraimage',
            field=models.ImageField(blank=True, null=True, upload_to='placeToUpload'),
        ),
        migrations.AddField(
            model_name='product',
            name='Coreimage',
            field=models.ImageField(blank=True, null=True, upload_to='placeToUpload'),
        ),
        migrations.AddField(
            model_name='product',
            name='Covergimage',
            field=models.ImageField(blank=True, null=True, upload_to='placeToUpload'),
        ),
        migrations.AddField(
            model_name='product',
            name='Frontimage',
            field=models.ImageField(blank=True, null=True, upload_to='placeToUpload'),
        ),
    ]
